### ISSUE TITLE
Feature request - in-app dialog box for devices

### ISSUE THREAD

**Issue by sjcwork** [mindwolf80/bin#3]
Would it be possible to add a selector for devices like this:

Option 1: a dialog box in the app allowing user to input IPs directly, i.e. not having to supply a TXT/CSV/XLSX file. This would help for small lists or single-device runs.
Option 2: the existing TXT/CSV/XLSX file dialog

**Comment by mindwolf80** [comment]
Try the nogui version. it's got all the functionality until I build a better interface.
