### ISSUE TITLE
NXOS copy run start

### ISSUE THREAD

**Issue by sjcwork** [mindwolf80/bin#4]
"copy run start" does not seem to complete when run on NX-OS. For example, these commands:

copy run start
sh start | in "saved at"

The first line does not complete and the second never runs. Maybe this has something to do with the hard-coded device type?
https://github.com/mindwolf80/Lab/blob/3a7a6de2e75d1d800d626ba5fa2b483d65c9fa7b/nice-1.2.0/nice-1.2.0.py#L110

**Comment by mindwolf80** [comment]
correct, as it was hardcoded with IOS which oddly works on most devices. (I think because of it's older linux shell code)

device types addedc and selectable at startup menu so the user won't forget:

cisco_asa, cisco_ftd, cisco_nxos, cisco_ios, f5_linux, f5_tmsh, linux, paloalto_panos
